FROM bitnami/kafka:latest

# Copia el archivo producer-app.js al contenedor
COPY producer-app.js /app/producer-app.js

# Establece el directorio de trabajo
WORKDIR /app

# Instala las dependencias necesarias para ejecutar producer-app.js (si las hay)

# Define el comando para ejecutar producer-app.js
CMD ["node", "producer-app.js"]
